### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jonathan-benn** [jordao76/hello-lights#1]
Hi,

Recently, when trying to install **hello-lights** on a brand new laptop, I encountered the following errors:

> C:\Users\MTL2_ADMIN\Desktop\laptop-traffic-light>npm install hello-lights
> 
> usb-detection@4.3.0 install C:\Users\MTL2_ADMIN\Desktop\laptop-traffic-light\node_modules\usb-detection
> prebuild-install || node-gyp rebuild
> 
> prebuild-install WARN install No prebuilt binaries found (target=10.16.0 runtime=node arch=x64 libc= platform=win32)
> 
> C:\Users\MTL2_ADMIN\Desktop\laptop-traffic-light\node_modules\usb-detection>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
> gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
> gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
> gyp ERR! System Windows_NT 10.0.17763
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\MTL2_ADMIN\Desktop\laptop-traffic-light\node_modules\usb-detection
> gyp ERR! node -v v10.16.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! usb-detection@4.3.0 install: `prebuild-install || node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the usb-detection@4.3.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\MTL2_ADMIN\AppData\Roaming\npm-cache\_logs\2019-07-19T20_17_50_317Z-debug.log

**Comment by jordao76** [comment]
For the time being, you should build usb-detection locally, by installing the npm build tools. I think the node installer also has an option to install them. I had already reported this here: https://github.com/MadLittleMods/node-usb-detection/issues/85

**Comment by jordao76** [comment]
You can now use `npm install hello-lights --no-optional`, and `usb-detection` will not be installed.

**Comment by jonathan-benn** [comment]
Thanks! The package management is a bit awkward (in `package.json` I need to add a new line to `scripts`... `"preinstall": "npm install hello-lights@^0.1.8 --no-optional"`). However, it works! 👍
